# Generated by Django 5.0.4 on 2024-05-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
